name: Java CI

on:
  [ "push" ]

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    environment: base
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Checkout project sources
        uses: actions/checkout@v2
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test
        run: ./gradlew cucumberCli -Drp.endpoint=${{ secrets.RP_ENDPOINT }} -Drp.project=${{ secrets.RP_PROJECT }} -Drp.uuid=${{ secrets.RP_UUID }} -Drp.launch=${{ secrets.RP_LAUNCH }} -Duser.login=${{ secrets.USER_LOGIN }} -Duser.password=${{ secrets.USER_PASSWORD }}