name: Java CI

on: [ push ]

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test
        run: ./gradlew test -Drp.endpoint=${{env.RP_ENDPOINT}} -Drp.project=${{env.RP_PROJECT}} -Drp.uuid=${{env.RP_UUID}} -Drp.launch=${{env.RP_LAUNCH}}
